apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: pds
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: test-container
          image: ghcr.io/sultanyasin1/my-nextjs-app@sha256:e23c42e2f90619dfbb3c5a2126e68fe3c88ef6a81c61fa0bb2db5c6e553570cb
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DATABASE_PASSWORD
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: API_TOKEN